### ISSUE TITLE
Kanban board set-up

### ISSUE THREAD

**Issue by Hope1226** [Hope1226/space-travelers-hub-app#25]
This issue is created to report to the reviewer that the kanban board for this Capstone project has been successfully implemented and can be checked via the following link:

[space-travelers-hub-project](https://github.com/Hope1226/space-travelers-hub-app/projects/1)

In this Capstone, we are working in a group of two people:
1. @Ntwali-Josue 
2. @Hope1226

**Comment by eri8-9** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- Well done!

![Felix](https://media.giphy.com/media/hlQeY3PbhH3i/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
